### PR TITLE
Don't register a TypeSerializer for arbitrary Number subclasses

### LINKED ISSUE #121: NumberSerializer is horribly broken, and can cause data loss
Configurate's built-in [`NumberSerializer`](https://github.com/SpongePowered/configurate/blob/4bc49644ed4ffd5a458b9367cf7d16de8a485495/configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/serialize/TypeSerializers.java#L93) will properly serialize any class extending `Number`. However, when it deserializes a type, it will *silently ignore* all but a few hardcoded subclasses of `Number`. If the loaded config is later saved, data sill be silently deleted if any other subclasses of `Number` are used (e.g. `BigDecimal`).

Since Configurate doesn't even log a warning, developers will have no idea where their data loss is coming from.

### PR DESCRIPTION
**Pull request by Aaron1011**
We have no way way to construct arbitrary subclasses of Number. By
registering a predicate that accepts only kown subclasses, we ensure
that users attempting to serialize an unknown Number subclass get a
proper exception, instead of a silent deserialization failure.

Fixes #121

### CODE REVIEW

**Comment by Aaron1011** [comment]
I'd like to get this merged as soon as possible, as it fixes a fairly severe issue.

**Comment by lucko** [comment]
I'm fine with the change, but we need to make a decision about whether "backwards incompatible" bug fixes are being merged or not before 4.0. (see discussion in #120)

**Comment by Aaron1011** [comment]
From my perspective, any plugin currently relying on `NumberSerializer` for custom `Number` types is already broken. IMHO, having an exception thrown is much better than continuing to silently lose data every time the config is loaded.

File: configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/serialize/TypeSerializers.java [hunk 1]
```diff
@@ -91,6 +92,20 @@ public void serialize(@NonNull TypeToken<?> type, @Nullable String obj, @NonNull
...
+        public static Predicate<TypeToken<Number>> getPredicate() {
+            return (type) -> {
+                type = type.wrap();
+                Class<?> clazz = type.getRawType();
+                return Integer.class.equals(clazz)
+                        || Long.class.equals(clazz)
+                        || Short.class.equals(clazz)
+                        || Byte.class.equals(clazz)
+                        || Float.class.equals(clazz)
+                        || Double.class.equals(clazz);
```
Comment (ryantheleach) [inline configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/serialize/TypeSerializers.java]: I would have expected more types then this being supported by default. BigDecimal?

Comment (Aaron1011) [reply configurate-core/src/main/java/ninja/leaping/configurate/objectmapping/serialize/TypeSerializers.java]: My intent with this PR is just to fix the behavior of the existing serialized. We could probably add support for BigDecimal in another PR

**Comment by Aaron1011** [comment]
@Zidane Thoughts on whether or not this should constitute a breaking change?

**Comment by Zidane** [comment]
I am of the opinion it isn't breaking because it is inherently broken and it is our responsibility to mitigate that over a "technical break" with the exception being thrown.

**Comment by ryantheleach** [comment]
@Aaron1011 @Zidane would https://github.com/SpongePowered/configurate/issues/95 be considered in the same boat then? It prevents serialization of some DataContainers / NBT.
