### PR TITLE
fix: include field annotations in AnnotatedType

### LINKED ISSUE #350: AnnotatedType in Annotated TypeSerializers is missing annotations on the field
The AnnotatedType passed into TypeSerializer.Annotated methods does not have the annotations from the field if used from an ObjectMapper

### PR DESCRIPTION
**Pull request by Machine-Maker**
Previously, only TYPE_USE annotations were included in the AnnotatedType from fields in an ObjectMapper. This updates the AnnotatedType to include the field annotations. Added a test to ensure this behavior.

Fixes #350

### CODE REVIEW

File: core/src/main/java/org/spongepowered/configurate/objectmapping/ObjectFieldDiscoverer.java [hunk 1]
```diff
@@ -149,7 +150,7 @@ private void collectFields(final AnnotatedType clazz, final FieldCollector<Map<F
 
             field.setAccessible(true);
             final AnnotatedType fieldType = getFieldType(field, clazz);
-            fieldMaker.accept(field.getName(), fieldType, Types.combinedAnnotations(fieldType, field),
+            fieldMaker.accept(field.getName(), updateAnnotations(fieldType, field.getAnnotations()), Types.combinedAnnotations(fieldType, field),
```
Comment (zml2008) [inline core/src/main/java/org/spongepowered/configurate/objectmapping/ObjectFieldDiscoverer.java:153]: This merging step would have to be done on every FieldDiscoverer implementation individually -- maybe there's a more thorough way of implementing this, say by doing the annotation merge using the AnnotatedElement provided within the `fieldMaker` instead?

Otherwise this would require changes to both the kotlin data class discoverer, and the record discoverer

(in addition to the future constructor-based discoverer)

**Review by zml2008 — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/spongepowered/configurate/objectmapping/ObjectFieldDiscoverer.java (hunk 1 above)
Comment (Machine-Maker) [reply core/src/main/java/org/spongepowered/configurate/objectmapping/ObjectFieldDiscoverer.java]: Ok, I moved it to where the FieldData is created in the ObjectMapperFactoryImpl

File: core/src/main/java/org/spongepowered/configurate/objectmapping/ObjectFieldDiscoverer.java [hunk 2]
```diff
@@ -19,6 +19,7 @@
 import static io.leangen.geantyref.GenericTypeReflector.erase;
 import static io.leangen.geantyref.GenericTypeReflector.getExactSuperType;
 import static io.leangen.geantyref.GenericTypeReflector.getFieldType;
+import static io.leangen.geantyref.GenericTypeReflector.updateAnnotations;
```
Comment (zml2008) [inline core/src/main/java/org/spongepowered/configurate/objectmapping/ObjectFieldDiscoverer.java:22]: unused import

**Review by zml2008 — CHANGES_REQUESTED** [review]

**Review by zml2008 — APPROVED** [review]
